### PR TITLE
feat: env loader nested values

### PR DESCRIPTION
**Pull request by Kit-p**
@ekil1100
Hi Like! This is Kit.

Saw your comment about wanting to contribute to oven-sh/bun#248.
I would like to invite you for collaboration, we can co-author a PR.

I made a commit ([link](https://github.com/ekil1100/bun/pull/1/commits/2ed5020ae46d3ae78fc26faad2c62c444c47cb36)) for the issue, but unfortunately could not test it due to hardware limitations.
Would you mind help run the unit test to ensure the commit's behavior is correct?

### CODE REVIEW

**Comment by ekil1100** [comment]
@Kit-p Hi Kit, I will try to run the test, and will comeback to you with the result.

**Comment by ekil1100** [comment]
@Kit-p I was trying to build the bun, I can't get `make vendor identifier-cache jsc dev` to work. I post the issue on [discord](https://discord.com/channels/876711213126520882/888839314056839309/1020590875404939274).

```
clang-13: error: no such file or directory: 'src/bun.js/debug-bindings-obj/io_darwin.o'
make: *** [headers] Error 1
```

Do you know how to fix it?

**Comment by Kit-p** [comment]
Hi Like, have you tried the following comment (and also the one below it)? The Makefile may be the cause.

https://github.com/oven-sh/bun/issues/1181#issuecomment-1233769442

**Comment by ekil1100** [comment]
@Kit-p Do you mean run `make bindings`? Let's chat on discord, my username is `Ekil#1759`.

**Pull request closed without merging**
